version: '3'

services:
  web:
    build: .
    command: gunicorn office_booking.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    networks:
      - net
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=booking
      - DJANGO_DB_USER=admin
      - DJANGO_DB_PASSWORD=12345678

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  postgres_data:
